config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  post 'users/update'

  get '/categories/:id' => 'categories#show', :as => 'category'
  get '/subject/:id' => 'subjects#show', :as => 'subject'
  get '/discussion/:id' => 'discussions#show', :as => 'discussion'
  get 'search', to: 'discussions#search'
  get '/faq', to: 'pages#faq'

  resources :users, only: %i[edit update]
  resources :personal_messages, only: %i[create new]
  resources :conversations, only: %i[index show]

  resources :profiles do
    member do
      put 'bans/update'
    end
  end

  resources :discussions do
    member do
      resources :posts
    end
  end

  root to: 'pages#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :subjects

  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: { scope: :receiver }

  scope :participating, lambda { |user|
    where('(conversations.author_id = ? OR conversations.receiver_id = ?)', user.id, user.id)
  }

  scope :between, lambda { |sender_id, receiver_id|
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  }

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/models/discussion.rb
# frozen_string_literal: true

class Discussion < ApplicationRecord
  belongs_to :subject
  belongs_to :user
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
  validates :content, presence: true, length: { minimum: 5, maximum: 5000 }
end

app/models/personal_message.rb
# frozen_string_literal: true

class PersonalMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
  paginates_per 15

  validates :content, presence: true, length: { minimum: 4, maximum: 5000 }
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  belongs_to :category
  has_many :discussions
  paginates_per 20

  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: %w[Admin Moderator Regular Banned]
  before_create :assign_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :discussions

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy

  validates :user_name, presence: true, length: { minimum: 3, maximum: 15 } 

  has_attached_file :avatar, styles: { regular: "255x255>", medium: "150x150>", discussion: "120x120>", tiny: "30x30>" }, default_url: ":style/default_avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  private

  def assign_role
    self.role ||= :Regular if new_record?
  end
end

app/controllers/bans_controller.rb
# frozen_string_literal: true

class BansController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user

  def update
    @user = User.find(params[:profile_id])
    @is_ban
    if @user.role == 'Regular'
      @user.role = 'Banned'
      @is_ban = true
    else
      @user.role = 'Regular'
      @is_ban = false
    end
    @user.save!

    respond_to do |format|
      format.js
    end
  end

  private

  def check_user
    redirect_to root_path unless current_user.role == 'Admin'
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @categories = Category.all.order('created_at ASC')
  end

  def faq; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[edit update]

  def create
    @discussion = Discussion.find(params[:id])
    @post = current_user.posts.build(post_params)
    @post.discussion = @discussion
    respond_to do |format|
      if @post.save
        format.html do
          redirect_to discussion_path(params[:id])
        end
      else
        format.html do
          render 'new'
        end
       end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html do
          redirect_to discussion_path(@post.discussion), notice: 'Your post has been edited'
        end
      else
        render 'edit'
      end
    end
  end

  def destroy; end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :user_restrictions, only: [:edit]
  def show
    @profile = User.find(params[:id])
  end

  def edit; end

  private

  def user_restrictions
    @profile = User.find(params[:id])
    return false unless @profile == current_user
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to profile_path(@user)
    else
      render 'profile/edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :description,
      :age,
      :website,
      :facebook,
      :twitter,
      :instagram,
      :location,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bans_helper.rb
# frozen_string_literal: true

module BansHelper
  def check_ban
    @is_ban ? 'Unblock User' : 'Ban User'
  end

  def check_if_banned(role)
    role == 'Regular' ? 'Ban User' : 'Unblock User'
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
  def all_posts(discussions)
    posts = 0
    discussions.each do |discussion|
      posts += discussion.posts.count
    end
    posts
  end
end

app/helpers/discussions_helper.rb
# frozen_string_literal: true

module DiscussionsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/helpers/subjects_helper.rb
# frozen_string_literal: true

module SubjectsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/profiles/edit.html.erb
<div class="container">
	<h2>Edit My profile</h2>
	<%= simple_form_for @profile do |f| %>
		<%= f.input :age %>
		<%= f.input :location %>
		<%= f.input :website %>
		<%= f.input :twitter %>
		<%= f.input :facebook %>
		<%= f.input :instagram %>
		<%= f.input :description, as: :text %>
		<p>Upload Avatar</p>
		<%= f.file_field :avatar %>
		<br><br><br>
		<%= f.button :submit, "Edit Profile", :class=>"btn btn-lg btn-warning" %>
	<% end %>
</div>

app/views/profiles/show.html.erb
<div id="user-profile-2" class="user-profile">
		<div class="tabbable">
			<div class="tab-content no-border padding-24">
				<div id="home" class="tab-pane in active">
					<div class="row">
						<div class="col-xs-12 col-sm-3 center">
							<span class="profile-picture">
								<%= image_tag @profile.avatar.url(:regular), :class=>"img-fluid rounded-circle mt-3 ml-2" %>
							</span>

							<div class="space space-4"></div>
							<% if current_user != @profile && user_signed_in? %>
								<%= link_to  new_personal_message_path(receiver_id: @profile) do %>
									<button class="btn btn-sm btn-block btn-primary" style="background: #03a9f4; width: 96%;">
										<i class="ace-icon fa fa-envelope-o bigger-110"></i>
										<span class="bigger-110">Send a message</span>
									</button>
								<% end %>
							<% end %>
						</div>
						<div class="col-xs-12 col-sm-9">
							<h4 class="blue">
								<span class="middle"><%= @profile.user_name %></span>

								<span class="label label-purple arrowed-in-right">
									<% if user_signed_in? %>
										<% if current_user == @profile %>
											<%= link_to "Edit my profile", edit_profile_path(@profile), :class=>"btn btn-md btn-warning" %>
										<% elsif current_user.role == "Admin" %>
											<%= link_to check_if_banned(@profile.role), bans_update_profile_path(profile_id: @profile.id), :id=>"ban_user",
											:method => :put,:remote => true, :class=>"btn btn-md btn-danger" %>
										<% end %>
									<% end %>
								</span>
							</h4>

							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Username </div>
									<div class="profile-info-value">
										<span><%= @profile.user_name %></span>
									</div>
								</div>
								<div class="profile-info-row">
									<div class="profile-info-name"> Role </div>
									<div class="profile-info-value">
										<span><%= @profile.role %></span>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Location </div>

									<div class="profile-info-value">
										<i class="fa fa-map-marker light-orange bigger-110"></i>
										<%= @profile.location %>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Joined </div>

									<div class="profile-info-value">
										<span><%= @profile.created_at.strftime('%F') %></span>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Posts </div>

									<div class="profile-info-value">
										<span><%= @profile.posts.count %></span>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Age </div>

									<div class="profile-info-value">
										<span><%= @profile.age  %></span>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Last Online </div>

									<div class="profile-info-value">
										<span><%= @profile.last_sign_in_at %></span>
									</div>
								</div>
							</div>

							<div class="hr hr-8 dotted"></div>

							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Website </div>

									<div class="profile-info-value">
										<% if @profile.website %>
											<%= link_to "My website",  @profile.website %>
										<% end %>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name">
										<i class="middle ace-icon fa fa-facebook-square bigger-150 blue"></i>
									</div>

									<div class="profile-info-value">
										<% if @profile.facebook.present? %>
											<%= link_to "Find me on facebook",  @profile.facebook %>
										<% end %>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name">
										<i class="middle ace-icon fa fa-twitter-square bigger-150 light-blue"></i>
									</div>

									<div class="profile-info-value">
										<% if @profile.twitter.present? %>
											<%= link_to "Follow me on Twitter",  @profile.twitter %>
										<% end %>
									</div>
								</div>
								<div class="profile-info-row">
									<div class="profile-info-name">
										<i class="middle ace-icon fa fa-instagram bigger-150 light-blue"></i>
									</div>

									<div class="profile-info-value">
										<% if @profile.instagram.present? %>
											<%= link_to "Check my instagram",  @profile.instagram %>
										<% end %>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="space-20"></div>

					<div class="row">
						<div class="col-xs-12 col-sm-6">
							<div class="widget-box transparent">
								<div class="widget-header widget-header-small">
									<h4 class="widget-title smaller">
										About <%= @profile.user_name %>:
									</h4>
								</div>

								<div class="widget-body">
									<div class="widget-main">
										<% if @profile.description %>
										<%= @profile.description %>
										<% else %>
										<p class="text-muted">No description yet</p>
										<% end %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>