config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  post 'users/update'

  get '/categories/:id' => 'categories#show', :as => 'category'
  get '/subject/:id' => 'subjects#show', :as => 'subject'
  get '/discussion/:id' => 'discussions#show', :as => 'discussion'
  get 'search', to: 'discussions#search'
  get '/faq', to: 'pages#faq'

  resources :users, only: %i[edit update]
  resources :personal_messages, only: %i[create new]
  resources :conversations, only: %i[index show]

  resources :profiles do
    member do
      put 'bans/update'
    end
  end

  resources :discussions do
    member do
      resources :posts
    end
  end

  root to: 'pages#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :subjects

  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: { scope: :receiver }

  scope :participating, lambda { |user|
    where('(conversations.author_id = ? OR conversations.receiver_id = ?)', user.id, user.id)
  }

  scope :between, lambda { |sender_id, receiver_id|
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  }

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/models/discussion.rb
# frozen_string_literal: true

class Discussion < ApplicationRecord
  belongs_to :subject
  belongs_to :user
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
  validates :content, presence: true, length: { minimum: 5, maximum: 5000 }
end

app/models/personal_message.rb
# frozen_string_literal: true

class PersonalMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
  paginates_per 15

  validates :content, presence: true, length: { minimum: 4, maximum: 5000 }
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  belongs_to :category
  has_many :discussions
  paginates_per 20

  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: %w[Admin Moderator Regular Banned]
  before_create :assign_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :discussions

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy

  validates :user_name, presence: true, length: { minimum: 3, maximum: 15 } 

  has_attached_file :avatar, styles: { regular: "255x255>", medium: "150x150>", discussion: "120x120>", tiny: "30x30>" }, default_url: ":style/default_avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  private

  def assign_role
    self.role ||= :Regular if new_record?
  end
end

app/controllers/bans_controller.rb
# frozen_string_literal: true

class BansController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user

  def update
    @user = User.find(params[:profile_id])
    @is_ban
    if @user.role == 'Regular'
      @user.role = 'Banned'
      @is_ban = true
    else
      @user.role = 'Regular'
      @is_ban = false
    end
    @user.save!

    respond_to do |format|
      format.js
    end
  end

  private

  def check_user
    redirect_to root_path unless current_user.role == 'Admin'
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @categories = Category.all.order('created_at ASC')
  end

  def faq; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[edit update]

  def create
    @discussion = Discussion.find(params[:id])
    @post = current_user.posts.build(post_params)
    @post.discussion = @discussion
    respond_to do |format|
      if @post.save
        format.html do
          redirect_to discussion_path(params[:id])
        end
      else
        format.html do
          render 'new'
        end
       end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html do
          redirect_to discussion_path(@post.discussion), notice: 'Your post has been edited'
        end
      else
        render 'edit'
      end
    end
  end

  def destroy; end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bans_helper.rb
# frozen_string_literal: true

module BansHelper
  def check_ban
    @is_ban ? 'Unblock User' : 'Ban User'
  end

  def check_if_banned(role)
    role == 'Regular' ? 'Ban User' : 'Unblock User'
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
  def all_posts(discussions)
    posts = 0
    discussions.each do |discussion|
      posts += discussion.posts.count
    end
    posts
  end
end

app/helpers/discussions_helper.rb
# frozen_string_literal: true

module DiscussionsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/helpers/subjects_helper.rb
# frozen_string_literal: true

module SubjectsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
     <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_categories.html.erb
<div class="categories mb-5">
	<div class="category-bar mb-1">
		<div class="container">
			<div class="float-left p-2">
				<%= link_to category_path(category), class: "text-white" do%>
					<i class="fa fa-book fa-lg"></i> &nbsp;<%= category.name %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="topics">
		<% if category.subjects.count > 0 %>
			<table class="table table-hover">
					<thead>
					<tr>
						<th></th>
						<th>Discussions</th>
						<th>Posts</th>
						<th>Latest Discussion</th>
					</tr>
					</thead>
					<tbody>
					<% category.subjects.each do |subject| %>
					<tr>
						<td>
							<%= link_to subject_path(subject), class: "text-dark" do%>
								<i class="fa fa-file fa-2x"></i> &nbsp;<%= subject.name %>
							<% end %> 
						</td>
						<td><%= subject.discussions.count %></td>
						<td><%= all_posts(subject.discussions) %></td>
						<% if subject.discussions.last.present? %>
						<td> <%= link_to subject.discussions.last.name, discussion_path(subject.discussions.last),
						:class=>"text-dark" %><br>
						by: <%= link_to subject.discussions.last.user.user_name, profile_path(subject.discussions.last.user) %> </td>
						<% else %>
						<td> - </td>
						<% end %>
					</tr>
					<% end %>
					</tbody>
			</table>
		<% else %>
		<p class="text-center p-4">No subjects yet</p>
		<% end %>
	</div>
</div>

app/views/partials/_discussions.html.erb
<div class="topics">
			<table class="table table-hover">
					<thead>
					<tr>
						<th></th>
						<th>Posts</th>
						<th>Views</th>
						<th>Latest Posts</th>
					</tr>
					</thead>
					<tbody>
					<% discussions.each do |discussion| %>
					<tr>
						<td>
							<%= link_to discussion_path(discussion), class: "text-dark" do%>
								<i class="fa fa-file fa-2x"></i> &nbsp;<%= discussion.name %>
							<% end %> 
						</td>
						<td><%= discussion.posts.count %></td>
						<td><%= rand(500) %></td>
						<% if discussion.posts.last.present? %>
							<td>by: <%= link_to discussion.posts.last.user.user_name, profile_path(discussion.posts.last.user) %> 
							<br> at: <%= discussion.posts.last.created_at.strftime('%F - %T') %> </td>
						<% else %>
							<td> - </td>
						<% end %>
					</tr>
					<% end %>
					</tbody>
			</table>
</div>

app/views/partials/_footer.html.erb
<footer class="page-footer font-small blue pt-4">

 <footer id="footer" class="footer-1">
<div class="main-footer widgets-dark typo-light">
	<div class="container">
		<div class="row">
  
<div class="col-xs-12 col-sm-6 col-md-3">
	<div class="widget subscribe no-box">
		<h5 class="widget-title">DISCUSSION FORUM<span></span></h5>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quaerat explicabo repellat magnam officia nostrum excepturi nam sit similique, voluptates ipsa consectetur in ab cumque eveniet impedit? Dolores veniam et ipsam adipisci, facere tempora repudiandae. </p>
	</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Quick Links<span></span></h5>
<ul class="thumbnail-widget">
	<li>
		<div class="thumb-content"><a href="#.">Link #1</a></div>	
	</li>
	<li>
		<div class="thumb-content"><a href="#.">Link #2</a></div>	
	</li>
	<li>
		<div class="thumb-content"><a href="#.">Link #2</a></div>	
	</li>
	<li>
		<div class="thumb-content"><a href="#.">Link #3</a></div>	
	</li>
	<li>
		<div class="thumb-content"><a href="#.">Link #3</a></div>	
	</li>
	<li>
		<div class="thumb-content"><a href="#.">Link #4</a></div>	
	</li>
	<li>
		<div class="thumb-content"><a href="#.">Link #5</a></div>	
	</li>
</ul>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Get Started<span></span></h5>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, at?</p>
<%= link_to "Register on forum", new_user_registration_path, :class=>"btn btn-lg btn-warning" %>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
	<div class="widget no-box">
	<h5 class="widget-title">Contact Us<span></span></h5>
	<p><a  class="text-black">contact@example.com</a></p>
	<ul class="social-footer2">
		<li class="">
			<a target="_blank" href="https://www.youtube.com/">
				<i class="fa fa-youtube-play fa-2x"></i>
			</a>
		</li>
		<li class="">
			<a href="https://www.facebook.com/" target="_blank" title="Facebook">
				<i class="fa fa-facebook-f fa-2x"></i>
			</a></li>
		<li class="">
			<a href="https://twitter.com" target="_blank" title="Twitter">
				<i class="fa fa-twitter fa-2x"></i>
			</a></li>
		<li class="">
			<a title="instagram" target="_blank" href="https://www.instagram.com/">
				<i class="fa fa-instagram fa-2x"></i>
			</a>
		</li>
	</ul>
	</div>
</div>

		</div>
	</div>
</div>
  
<div class="footer-copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<p><i>Copyleft H3BCKN ©2019. All rights not reserved</i></p>
			</div>
		</div>
	</div>
</div>
</footer>

</footer>

app/views/partials/_header.html.erb
<header>
<div class="container-fluid">
    <section class="row no-gutter align-items-center">
        <div class="col-lg-12 text-center p-0 d-flex align-items-center">
            <img class="img-fluid position-relative mx-auto" src="https://picsum.photos/1400/320" alt="">
            <h1 class="w-100 position-absolute text-white my-auto">Forum<br>Enjoy your interesting discussions</h1>
        </div>
    </section>
</div>

<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path, :class=>"navbar-brand text-light" do %>
  	<img src="https://pngimage.net/wp-content/uploads/2018/06/logo-placeholder-png-6.png" alt="" class="img-fluid rounded" width="40px" height="40px">
  Forum
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#demo-navbar" aria-controls="demo-navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="demo-navbar">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to profile_path(current_user), :class=>"nav-link text-light" do  %>
           <%= image_tag current_user.avatar.url(:tiny), :class=>"rounded-circle" %>&nbsp; <%= current_user.user_name %></span>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to destroy_user_session_path, :method => :delete, :class=>"nav-link text-light" do  %>
           <i class="fa fa-sign-out fa-lg"></i>&nbsp; Logout </span>
        <% end %>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to new_user_registration_path, :class=>"nav-link text-light" do  %>
           <i class="fa fa-user-plus fa-lg"></i>&nbsp;Register<span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path, :class=>"nav-link text-light" do  %>
           <i class="fa fa-sign-in fa-lg"></i></i>&nbsp;Login
        <% end %>
      </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Quick Links
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" >1</a>
          <a class="dropdown-item" >2</a>
          <a class="dropdown-item" >3</a>
          <a class="dropdown-item" >4</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" >5</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "FAQ", faq_path, :class=>"nav-link text-warning" %>
      </li>
    </ul>
    <%= form_tag(search_path, method: :get, class: "form-inline my-2 my-lg-0") do |f| %>
     <%= text_field_tag :q, "", class: 'form-control mr-sm-2', :placeholder => "Find discussions"%>
     <%= submit_tag("Search", class:"btn btn-outline-warning my-2 my-sm-0") %>
    <% end %>
  </div>
</nav>
</header>

app/views/partials/_navbox.html.erb
<% if user_signed_in? %>
<div class="card" style="width: 18rem;">
				<div class="text-center pt-2">
					<h5>Hello <%= current_user.user_name %>!</h5>
			  		<%= image_tag current_user.avatar.url(:medium), :class=>"img-fluid rounded-circle mt-3 ml-2" %>
			  	</div>
			  <div class="card-body">
			  	<% if current_user.admin %>
				  	<%= link_to rails_admin_path  do %>
				    <button class="btn btn-primary btn-block mb-3">
				    	<i class="fa fa-cogs"></i>
				    	Admin Panel
					</button>
				    <% end %>
			    <% end %>
			    <%= link_to profile_path(current_user)  do %>
			    <button class="btn btn-success btn-block mb-3">
			    	<i class="fa fa-home"></i>
			    	My profile
				</button>
			    <% end %>
			    <%= link_to conversations_path do %>
			    <button class="btn btn-warning btn-block mb-3">
			    	<i class="fa fa-envelope"></i>
			    	My Messages
				</button>
			    <% end %>
			    <%= link_to destroy_user_session_path, :method => :delete do %>
			    <button class="btn btn-danger btn-block mb-3">
			    	<i class="fa fa-sign-out"></i>
			    	Log out
				</button>
			    <% end %>
			</div>
</div>

<% else %>

<div class="card" style="width: 18rem;">	
	<div class="card-body">
			  <h5 class="text-center">Login</h5>
			  <%= form_for(:user, :url => session_path(:user)) do |f| %>
			  <div class="form-group">
				 <%= f.text_field :email, :class=>"form-control", :placeholder=>"email" %>
              </div>
               <div class="form-group">
            	<%= f.password_field :password, :class=>"form-control", :placeholder=>"password"  %>
               </div>
               <div class="form-group">
               	<%= f.check_box :remember_me %>
  				<%= f.label :remember_me %>
               </div>
                <div class="form-group">
                <%= f.submit "Log In", :class=>"btn btn-warning btn-block float-right" %>
                <br><br>
                 <%= link_to "Forgot your password?", new_password_path(:user) %>
                </div>
			  <% end %>
			  <%= link_to "Register", new_user_registration_path %>
	</div>
</div>

<% end %>

app/views/partials/_posts.html.erb
<div class="card" style="max-width: 100%;">
			<div class="row no-gutters">
			   <div class="col-sm-2">
			    <%= image_tag post.user.avatar.url(:discussion), :class=>"img-fluid rounded-circle mt-3 ml-2" %>
			    <p class="ml-4">
			    	 <p class="ml-4"><%= link_to post.user.user_name, profile_path(post.user), :class=>"text-dark" %>
			    	<br>
			    	<small><%= post.user.role %></small><br>
			    	<small>Posts: <%= post.user.posts.count %></small><br>
					<small>On forum since: <%= post.user.created_at.strftime('%F') %></small>	
			    </p>
				</p>

			    </div>
			    <div class="col-sm-10">
			      <div class="card-body" id="<%= index+1 %>">
			        <a href="#<%= index+1 %>" class="card-text text-dark">#<%=index+1 %>&nbsp;<small class="text-muted"><%= post.created_at.to_formatted_s(:db) %></small></a>
			        <p class="card-text container">
			        <%= simple_format(post.content) %>
			       <% if current_user == post.user && post.created_at > 30.minutes.ago && current_user.role != "Banned" %>
			        <%= link_to "Edit Post", edit_post_path(post), :class=>"btn btn-warning btn-md" %>
			        <% end %>
			    </p>
			</div>
		</div>
	</div>
</div>

app/views/partials/_search_discussions.html.erb
<div class="topics">
			<table class="table table-hover">
					<thead>
					<tr>
						<th></th>
						<th>Posts</th>
						<th>Subject</th>
						<th>Latest Posts</th>
					</tr>
					</thead>
					<tbody>
					<% discussions.each do |discussion| %>
					<tr>
						<td>
							<%= link_to discussion_path(discussion), class: "text-dark" do%>
								<i class="fa fa-file fa-2x"></i> &nbsp;<%= discussion.name %>
							<% end %> 
						</td>
						<td><%= discussion.posts.count %></td>
						<td><%= link_to discussion.subject.name, subject_path(discussion.subject) %></td>
						<% if discussion.posts.last.present? %>
							<td>by: <%= link_to discussion.posts.last.user.user_name, profile_path(discussion.posts.last.user) %> 
							<br> at: <%= discussion.posts.last.created_at.strftime('%F - %T') %> </td>
						<% else %>
							<td> - </td>
						<% end %>
					</tr>
					<% end %>
					</tbody>
			</table>
</div>